### ISSUE TITLE
Add Credit to Images of coverx.vercel.app

### ISSUE THREAD

**Issue by slowlydev** [boostvolt/icover#3]
Hey there, I recently noticed that some of the images used in your app are the same ones I created for my previous project, [CoverX](https://coverx.vercel.app/). I love to see other solutions to problems.  However, I kindly request proper credit for the usage of my Images. Please consider adding an acknowledgment section, mentioning the images sourced from [CoverX](https://coverx.vercel.app/). Maybe something similar I did in the "Unsplash section" of [CoverX](https://coverx.vercel.app/). This will encourage collaboration and respect within the community.

Thank you for reading this Issue
- Slowlydev

**Comment by boostvolt** [comment]
Sure. Now implemented.

<img width="305" alt="Bildschirmfoto 2023-08-07 um 13 16 08" src="https://github.com/boostvolt/icover/assets/51777660/552254a6-b0cd-4159-a2f5-d477114b339e">
<img width="537" alt="Bildschirmfoto 2023-08-07 um 13 16 14" src="https://github.com/boostvolt/icover/assets/51777660/639bbdd9-2fad-482f-820c-56f211afb673">

**Comment by slowlydev** [comment]
Thank you, I appreciate it. 😄
